In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data=pd.read_csv('/content/drive/MyDrive/datasets/BIKE DETAILS.csv')

In [ ]:
data.head()

,name,selling_price,year,seller_type,owner,km_driven,ex_showroom_price
0,Royal Enfield Classic 350,175000,2019,Individual,1st owner,350,NaN
1,Honda Dio,45000,2017,Individual,1st owner,5650,NaN
2,Royal Enfield Classic Gunmetal Grey,150000,2018,Individual,1st owner,12000,148114.0
3,Yamaha Fazer FI V 2.0 [2016-2018],65000,2015,Individual,1st owner,23000,89643.0
4,Yamaha SZ [2013-2014],20000,2011,Individual,2nd owner,21000,NaN

In [ ]:
data.isna().sum()

name                   0
selling_price          0
year                   0
seller_type            0
owner                  0
km_driven              0
ex_showroom_price    435
dtype: int64

In [ ]:
data['ex_showroom_price'] = data['ex_showroom_price'].fillna(0)

In [ ]:
data.head()

,name,selling_price,year,seller_type,owner,km_driven,ex_showroom_price
0,Royal Enfield Classic 350,175000,2019,Individual,1st owner,350,0.0
1,Honda Dio,45000,2017,Individual,1st owner,5650,0.0
2,Royal Enfield Classic Gunmetal Grey,150000,2018,Individual,1st owner,12000,148114.0
3,Yamaha Fazer FI V 2.0 [2016-2018],65000,2015,Individual,1st owner,23000,89643.0
4,Yamaha SZ [2013-2014],20000,2011,Individual,2nd owner,21000,0.0

In [ ]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

for i in ['name','seller_type','owner']:
  data[i]= label_encoder.fit_transform(data[i])
  data[i].unique()

In [ ]:
data.head()

   name  selling_price  year  seller_type  owner  km_driven  ex_showroom_price
0   179         175000  2019            1      0        350                0.0
1   145          45000  2017            1      0       5650                0.0
2   183         150000  2018            1      0      12000           148114.0
3   260          65000  2015            1      0      23000            89643.0
4   269          20000  2011            1      1      21000                0.0

In [ ]:
y=data['ex_showroom_price']
x=data.drop(['ex_showroom_price'],axis=1)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.25)

In [34]:
from sklearn import linear_model
lr=linear_model.LinearRegression()

model=lr.fit(x_train,y_train)

In [35]:
a=model.predict(x_test)

In [36]:
print(a)

[ 31836.99167259  14164.54614493  25179.83809871  22012.80944771
  81158.51919752  24044.03546806  18427.85124828  24546.41556612
  31897.34791708  42170.88825983  29147.52918268  15777.72652127
  86224.24717115  41761.75329736  79460.29555238  36718.15319736
  64436.77372162  49184.93133936  35679.83420804  92923.19154162
  22252.11817276  59665.85358247  27707.38310174  16877.06815358
  61972.72701982  36937.71099482  16814.96199028  28186.21304907
  48171.93216022 105641.07634583  40308.17585432  23569.9457709
  19127.68025412  31345.51297961  35883.93448993  12734.01480783
  40281.87547432  37081.56421169  59409.70300439  35829.65256788
 137952.30610154  21915.95073599  35179.33398439  41042.79155479
  28271.14518955  33653.20640755  26121.40621735  57280.6500618
  41788.49633929  11658.59018757  20872.29194701 148305.33378544
  32842.67189793  82778.63074561  57512.95300116 120763.10095332
 136225.00817193  29327.55145858  31396.23571297  58485.92551215
  12636.9153298   27016.96906634  32749.66852357  38793.29327466
  32269.01922648  24560.28060023  24910.50071715  25541.53818528
 148041.63087573  98117.19487451  23516.51175027  32301.68048091
 143059.44905431 115927.38221859  42798.3077089   26396.60707497
  21257.13743754  24763.75233642  24137.46305119 164077.22029289
  58443.02564245  59793.97475954  73019.17253986 253423.3147377
  35908.23406186  39094.51295772 364885.55429595  70754.71398054
  46191.02987462  26609.81270101  24656.9462628   16511.97155432
  34195.82824658  35249.71330692  31680.29158755  97673.45266569
  16723.86716439  67183.64050841  49936.37715299 120771.2100061
  20387.05969775  48412.71209535 158304.02306334  38997.56507087
  36939.22852979  75656.66347794 103316.13743705  54973.98780603
  25011.46372396  43761.81913403  42540.61550265  63001.00215776
  34828.90422657  30071.07498891  19546.80622168 155398.68734754
  28504.60193905 142744.62767322  68661.70720601 103534.27552097
  29040.08718222  37877.95539778  26881.00785899  61146.62533648
  28999.38055328 111105.52604218  25062.72284675  25594.06566977
  21231.15437001  33372.86562061  88874.35033597  44911.14087299
  45975.10520552  55328.63703856  33917.88667051  76581.01008621
  63720.70138615  46976.89556449 108748.29810605  51656.95007215
  87509.46573157  58517.95792214  46622.48480321  22541.04131978
  34733.71862895  22768.18446242  24494.65043229  36635.46936885
  70650.88280373  15391.39191569 130458.86738538  22732.55795738
  29806.53420552  72734.62367057  25854.92872043  67146.00607085
  57159.83048457  29131.1989254   38480.84146591  51168.90550533
  39175.6312664   39056.23335415  62593.26708902  26402.2631755
  15773.15319375  67175.00250536  44016.49231035  32012.27634674
 116594.43356289  23891.72918011  97695.2677091   58214.915502
  34766.54597488  25096.22148773  19105.79175388  32761.39257777
  64997.86687354  30416.79319826  46084.74601201  34482.32741377
  19925.01549855  70294.04966252 123051.73094192  15890.53436469
  99087.50290815  20636.3032516   52361.84923558  39690.1368419
  35606.85362588  79461.25971287 131791.45843559  30292.2374691
  33071.99103298  36237.52250156  43288.87877119  36301.55552769
  20524.08437456  36061.56504545  28675.64299669  37895.45229414
  40560.43894229  21404.46277128  32935.06289588  35802.12253421
  27994.05803268  23665.21972345  98050.03398455  75656.66347794
  34134.23320947  28247.95758246  77031.58984012  14770.02157967
  22064.55061471  55471.89058125  32423.27136329  66476.48332578
  32805.83717526  26001.27309967  25107.36901931 130964.81771953
  32495.66910612  23333.10526193  78850.22738052  53269.64327807
  69912.75280586  63399.44609375  23461.77546559  11963.73093324
  34407.09154966  22445.06056371  39566.03083237  24379.03116779
  30657.21168896  55017.09353023  29800.33662297  29585.66181483
  36612.4802377   28725.16517305  30261.96488064  34361.51651116
 161957.1419775   58515.63310686  30136.96023034  64316.11051105
  18778.55934882  54734.18849645  28442.69030679  70617.61447092
  31788.44640438  30605.17097235  17221.63283971  90254.82996029
  12579.55302169  22224.33349598  52481.76953066  37156.0969703
  51064.31284654  42263.11353648  31884.15954496  40770.08576243
  54709.85102413 123569.48310345  39964.5549396  114067.19035024
  23781.11783422 215245.82982473]

In [37]:
data.head()

   name  selling_price  year  seller_type  owner  km_driven  ex_showroom_price
0   179         175000  2019            1      0        350                0.0
1   145          45000  2017            1      0       5650                0.0
2   183         150000  2018            1      0      12000           148114.0
3   260          65000  2015            1      0      23000            89643.0
4   269          20000  2011            1      1      21000                0.0

In [38]:
aa=[[179,175000,2019,1,0,350]]

In [40]:
a=model.predict(aa)
print(a)

[143347.94612509]

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(